name: Pull Request CI

on:
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '15.x'
    - run: |
        npm ci
        npm test
        sed -i '/out\//d' .gitignore
        sed -i '/out-wpt\//d' .gitignore
    - id: deployment
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        expires: 30d
        channelId: prs-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}
    - uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Previews, as seen at the time of posting this comment:
          [**Run this PR's tests live**](${{ steps.deployment.outputs.details_url }}/standalone/)
          <sub>${{ github.event.pull_request.head.sha }}</sub>
          <!--
          pr;label;sha
          ${{ github.event.pull_request.number }};${{ github.event.pull_request.head.label }};${{ github.event.pull_request.head.sha }}
          -->
