# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request CI

on:
  pull_request_target:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14.x'
    - run: |
        cat << EOF
        ${{ toJSON(github) }}
        EOF
    - run: node --version
    - run: npm --version
    - run: npm ci
    - run: npm test
